### ISSUE TITLE
Getting "vscode module not found when attempting development

### ISSUE THREAD

**Issue by spikespaz** [be5invis/vscode-custom-css#44]
When initializing the environment using `npm install`, I get the following error:

```
spike@jacob-windows MINGW64 ~/Documents/github.com/be5invis/vscode-custom-css (master)
$ node .
module.js:549
    throw err;
    ^

Error: Cannot find module 'vscode'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\spike\Documents\github.com\be5invis\vscode-custom-css\src\extension.js:1:76)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Pressing the `F5` key does not work either.

**Comment by be5invis** [comment]
Well, this is a VSCode extension, not an NPM package.
It can only be run within VSCode.

**Comment by spikespaz** [comment]
Like I said, pressing the F5 key does not work either.

**Comment by be5invis** [comment]
Add `vscode` into devDependencies may solve this.
PRs are welcome.

**Comment by spikespaz** [comment]
I have already added the following to `package.json`.

```js
  "scripts": {
    "postinstall": "node ./node_modules/vscode/bin/install"
  },
  "devDependencies": {
    "typescript": "^2.6.1",
    "vscode": "^1.1.6",
    "eslint": "^4.11.0",
    "@types/node": "^7.0.43",
    "@types/mocha": "^2.2.42"
  },
  "dependencies": {
    "file-url": "^2.0.2",
    "xmlhttprequest": "^1.8.0"
  }```

**Comment by be5invis** [comment]
Then refer this article: https://code.visualstudio.com/docs/extensions/example-hello-world
Debugging Code extension **can not directly use** the normal NPM debugging settings.

**Comment by BenisonSam** [comment]
Is there any solution to this issue? Any updates!??
